### PR TITLE
Update to version 1.2

### PR DESCRIPTION
**Pull request by dhirschfeld**

### CODE REVIEW

**Comment by ericmjl** [comment]
ping @jakirkham @ocefpaf I'm not quite sure how to debug AppVeyor's issue here. Does it just require a restart?

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@ericmjl I asked the not to rerender. Let's see if that fixes AppVeyor.

**Comment by isuruf** [comment]
Can this be recipe be `noarch: python` ?

**Comment by ericmjl** [comment]
@isuruf I think so, but can I double-check, what are the requirements for it to be `noarch: python`?

**Comment by jakirkham** [comment]
Pure Python. No selectors in the recipes. No pre/post-[un]link scripts.

**Comment by dhirschfeld** [comment]
Conda did have a bug with noarch on Windows. Looks like the rerender has fixed it tho.

...except there's no Appveyor?

**Comment by jakirkham** [comment]
It's there. Have to scroll down in the status list to see it.

**Comment by dhirschfeld** [comment]
Looks like travis might need to be restarted?

**Comment by ericmjl** [comment]
All passed! Will merge in now.

**Pull request merged**
