### PR TITLE
Version bump 1.19 (fixes #2)

### LINKED ISSUE #2: Upstream version 1.1.9 is available
I am not sure what the best source for new versions is, but it might be a good idea to be in sync with pypi:

https://pypi.python.org/packages/54/9c/d5d6abd14c4c5dee1489b530da238004fed4ea76cf48a196ba8fe40baa17/autograd-1.1.9.tar.gz#md5=0a23c7d244fb4fb0a44a3c6711381ad0

### PR DESCRIPTION
**Pull request by richardotis**

### CODE REVIEW

**Comment by richardotis** [comment]
@jakirkham Any idea why the build is failing on Travis? This is only a version bump and the failure seems to be happening inside one of the conda forge scripts.

**Comment by jakirkham** [comment]
So first this should be a PR from your fork. If it is not a PR from your fork, but a branch on the main feedstock, then it will autodeploy packages once the CIs pass (before merging).

Second whenever doing a PR, it is good to just do a [re-rendering]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) of the feedstock. This updates all the feedstock content in some cases with input from the recipe.

**Comment by richardotis** [comment]
Thanks for the help @jakirkham . Re-rendering the feedstock fixed it and now 1.19 is deployed. I'll use my own fork for PRs in the future.

**Comment by jakirkham** [comment]
1.19 is only deployed for Linux, @richardotis. Will need a new PR to get the Mac and Windows packages released.

**Comment by richardotis** [comment]
Oops, let me get on that.

**Comment by richardotis** [comment]
Working on it in #4 now.

**Comment by jakirkham** [comment]
No worries. Just figured you would want to know. 😉

**Comment by richardotis** [comment]
@jakirkham Thanks for the help! Definitely appreciate all the work you've been putting in for the community on conda forge.

**Pull request closed without merging**
